### ISSUE TITLE
Please add a free/open source license

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ToastWallet/whyripple#1]
See title.

I don't have any preference, but currently your code is just publicly visible but 100% belongs to you.

**Comment by ToastWallet** [comment]
Hello

The code in this repo has been released as Public Domain

**Comment by MarkusTeufelberger** [comment]
Sorry, "public domain" is not a legal license in my country. Please use CC0 if you want to put this code in the public domain.

**Comment by ToastWallet** [comment]
I've added CC0 where Public Domain isn't applicable.

Thanks

**Comment by MarkusTeufelberger** [comment]
Thanks a lot!
